### ISSUE TITLE
为啥sys.io.query(q)里面的对象不能readJson呢

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#29]
```
2015-07-10 11:46:35,536 [qtp16119673-20] DEBUG org.nutz.walnut.web.module.AbstractWnModule - box:run: email list
2015-07-10 11:46:35,536 [qtp16119673-20] DEBUG org.nutz.walnut.impl.box.JvmAtom - Atom(0) before : email list
2015-07-10 11:46:35,550 [qtp16119673-20] DEBUG org.nutz.walnut.impl.box.JvmAtom - Atom[0] DONE
2015-07-10 11:46:35,550 [qtp16119673-20] WARN  org.nutz.walnut.impl.box.JvmAtom - Atom[0] ERROR: java.lang.NullPointerException
2015-07-10 11:46:35,551 [qtp16119673-20] WARN  org.nutz.walnut.impl.box.JvmAtom - Atom[0] ERROR: java.lang.NullPointerException
java.lang.NullPointerException
	at org.nutz.walnut.impl.io.WnBean.tree(WnBean.java:548)
	at org.nutz.walnut.impl.io.WnStoreFactoryImpl.get(WnStoreFactoryImpl.java:44)
	at org.nutz.walnut.impl.io.WnIoImpl.getInputStream(WnIoImpl.java:601)
	at org.nutz.walnut.impl.io.WnIoImpl.readJson(WnIoImpl.java:711)
	at org.nutz.walnut.ext.email.cmd_email.listLocalMail(cmd_email.java:136)
	at org.nutz.walnut.ext.email.cmd_email.exec(cmd_email.java:96)
	at org.nutz.walnut.impl.box.JvmAtom.__run(JvmAtom.java:39)
	at org.nutz.walnut.impl.box.JvmAtom.access$0(JvmAtom.java:36)
	at org.nutz.walnut.impl.box.JvmAtom$1$1$1.run(JvmAtom.java:76)
	at org.nutz.walnut.util.WnContext.su(WnContext.java:270)
	at org.nutz.walnut.impl.box.JvmAtom$1$1.run(JvmAtom.java:74)
	at org.nutz.walnut.util.WnContext.security(WnContext.java:160)
	at org.nutz.walnut.impl.box.JvmAtom$1.run(JvmAtom.java:72)
	at org.nutz.walnut.util.WnContext.hooking(WnContext.java:115)
	at org.nutz.walnut.impl.box.JvmAtom.run(JvmAtom.java:70)
	at org.nutz.walnut.impl.box.JvmAtomRunner.__run(JvmAtomRunner.java:204)
	at org.nutz.walnut.impl.box.JvmBox.run(JvmBox.java:77)
	at org.nutz.walnut.web.module.AbstractWnModule._run_cmd(AbstractWnModule.java:126)
	at org.nutz.walnut.web.module.AppModule.run(AppModule.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.nutz.mvc.impl.processor.MethodInvokeProcessor.process(MethodInvokeProcessor.java:25)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.AdaptorProcessor.process(AdaptorProcessor.java:33)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ActionFiltersProcessor.process(ActionFiltersProcessor.java:40)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ModuleProcessor.process(ModuleProcessor.java:113)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.walnut.web.processor.CreateWnContext.process(CreateWnContext.java:37)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.EncodingProcessor.process(EncodingProcessor.java:27)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.UpdateRequestAttributesProcessor.process(UpdateRequestAttributesProcessor.java:15)
	at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:40)
	at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:67)
	at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
	at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:183)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by zozoh** [comment]
添加了 TestCase:

```
AbstractWnIoTest.test_query_and_read
```
