### ISSUE TITLE
新建一个空文件，读取会抛错

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#54]
touch 一个新文件处理啊，然后 `/o/read/id:7m461q7h5qjlkr5c1ufin0a1gh`

会抛错:

```
WARN[qtp369241501-100]29T18:41:53.132: Error@/o/read/id:7m461q7h5qjlkr5c1ufin0a1gh :
java.lang.RuntimeException: java.io.IOException: Closed
    at org.nutz.lang.Lang.wrapThrow(Lang.java:151)
    at org.nutz.lang.Streams.writeAndClose(Streams.java:164)
    at org.nutz.mvc.view.RawView2.render(RawView2.java:40)
    at org.nutz.mvc.impl.processor.ViewProcessor.process(ViewProcessor.java:49)
    at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
    at org.nutz.mvc.impl.processor.MethodInvokeProcessor.process(MethodInvokeProcessor.java:28)
    at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
    at org.nutz.mvc.impl.processor.AdaptorProcessor.process(AdaptorProcessor.java:33)
    at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
    at org.nutz.mvc.impl.processor.ActionFiltersProcessor.process(ActionFiltersProcessor.java:58)
    at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
    at org.nutz.mvc.impl.processor.ModuleProcessor.process(ModuleProcessor.java:123)
    at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
    at org.nutz.walnut.web.processor.CreateWnContext.process(CreateWnContext.java:27)
    at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
    at org.nutz.mvc.impl.processor.EncodingProcessor.process(EncodingProcessor.java:27)
    at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
    at org.nutz.mvc.impl.processor.UpdateRequestAttributesProcessor.process(UpdateRequestAttributesProcessor.java:15)
    at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:44)
    at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:67)
    at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
    at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:196)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.nutz.walnut.jetty.WalnutFilter.doFilter(WalnutFilter.java:156)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:133)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:476)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:531)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Closed
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147)
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:96)
    at org.eclipse.jetty.servlets.GzipFilter$GzipStream.write(GzipFilter.java:530)
    at org.nutz.lang.Streams.write(Streams.java:142)
    at org.nutz.lang.Streams.write(Streams.java:106)
    at org.nutz.lang.Streams.writeAndClose(Streams.java:161)
    ... 46 more
INFO[qtp369241501-100]29T18:41:53.133: HTTPfail:9ms: /o/read/id:7m461q7h5qjlkr5c1ufin0a1gh
1631689 [qtp369241501-100] WARN org.eclipse.jetty.util.log - /o/read/id:7m461q7h5qjlkr5c1ufin0a1gh
java.lang.RuntimeException: java.io.IOException: CLOSED
    at org.nutz.lang.Lang.wrapThrow(Lang.java:151)
    at org.nutz.lang.Streams.writeAndClose(Streams.java:164)
    at org.nutz.mvc.view.RawView2.render(RawView2.java:40)
    at org.nutz.mvc.impl.processor.ViewProcessor.process(ViewProcessor.java:49)
    at org.nutz.walnut.web.processor.WnFailProcessor.process(WnFailProcessor.java:49)
    at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:49)
    at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:67)
    at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
    at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:196)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.nutz.walnut.jetty.WalnutFilter.doFilter(WalnutFilter.java:156)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:133)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:476)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:531)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CLOSED
    at org.eclipse.jetty.servlets.GzipFilter$GzipStream.checkOut(GzipFilter.java:585)
    at org.eclipse.jetty.servlets.GzipFilter$GzipStream.write(GzipFilter.java:529)
    at org.nutz.lang.Streams.write(Streams.java:142)
    at org.nutz.lang.Streams.write(Streams.java:106)
    at org.nutz.lang.Streams.writeAndClose(Streams.java:161)
    ... 33 more
```

**Comment by wendal** [comment]
木有重现啊
