### ISSUE TITLE
空文件，读取的时候有警告

### ISSUE THREAD

**Issue by zozoh** [zozoh/walnut#56]
如果 touch 一个文本文件。 然后用 `/o/read/id:xxxx` 去访问，服务器会打印错误日志:

```
44912 [qtp336484883-28] WARN org.eclipse.jetty.util.log - /o/read/id:63dd96a578galpnhljk1o0o3ca
java.lang.RuntimeException: java.io.IOException: CLOSED
    at org.nutz.lang.Lang.wrapThrow(Lang.java:151)
    at org.nutz.lang.Streams.writeAndClose(Streams.java:164)
    at org.nutz.mvc.view.RawView2.render(RawView2.java:40)
    at org.nutz.mvc.impl.processor.ViewProcessor.process(ViewProcessor.java:49)
    at org.nutz.walnut.web.processor.WnFailProcessor.process(WnFailProcessor.java:49)
    at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:49)
    at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:67)
    at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
    at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:196)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.nutz.walnut.jetty.WalnutFilter.doFilter(WalnutFilter.java:156)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:77)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:133)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:476)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:531)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CLOSED
    at org.eclipse.jetty.servlets.GzipFilter$GzipStream.checkOut(GzipFilter.java:585)
    at org.eclipse.jetty.servlets.GzipFilter$GzipStream.write(GzipFilter.java:529)
    at org.nutz.lang.Streams.write(Streams.java:142)
    at org.nutz.lang.Streams.write(Streams.java:106)
    at org.nutz.lang.Streams.writeAndClose(Streams.java:161)
    ... 33 more
```

好像 Nutz 的 RawView2 那边的问题？ @wendal  来看看？

**Comment by zozoh** [comment]
已经搞好了
